"""XOR fuzz tests: pure GDSFactory transistors vs live PyCell reference.

Generates transistor layouts from both the pure GDSFactory code
(ihp.cells.transistors) and the PyCell wrappers (ihp.cells2) across a
parameter matrix of W/L/NG, then does layer-by-layer kdb.Region XOR
to verify polygon-exact equivalence.
"""

from __future__ import annotations

import itertools

import klayout.db as kdb
import pytest

from ihp import PDK
from ihp import cells2 as pycell
from ihp.cells.transistors import nmos, nmos_hv, pmos, pmos_hv

# -----------------------------------------------------------------------
# Fixtures
# -----------------------------------------------------------------------


@pytest.fixture(autouse=True)
def activate_pdk():
    PDK.activate()


# -----------------------------------------------------------------------
# XOR engine
# -----------------------------------------------------------------------

SKIP_LAYERS = {(63, 0)}  # TEXT labels — not generated by pure GDSFactory


def xor_cells(ref, new):
    """Layer-by-layer kdb.Region XOR. Returns dict of failing layers."""
    kcell_ref = ref._kf_cell if hasattr(ref, "_kf_cell") else ref
    kcell_new = new._kf_cell if hasattr(new, "_kf_cell") else new
    layout_ref = kcell_ref.layout()
    layout_new = kcell_new.layout()
    dbu = layout_ref.dbu

    layers_ref = {}
    for li in layout_ref.layer_indices():
        info = layout_ref.get_info(li)
        key = (info.layer, info.datatype)
        r = kdb.Region(kcell_ref.begin_shapes_rec(li))
        if not r.is_empty():
            layers_ref[key] = r

    layers_new = {}
    for li in layout_new.layer_indices():
        info = layout_new.get_info(li)
        key = (info.layer, info.datatype)
        r = kdb.Region(kcell_new.begin_shapes_rec(li))
        if not r.is_empty():
            layers_new[key] = r

    all_layers = sorted(set(layers_ref) | set(layers_new))
    failures = {}

    for key in all_layers:
        if key in SKIP_LAYERS:
            continue
        in_ref = key in layers_ref
        in_new = key in layers_new
        if in_ref and not in_new:
            failures[key] = "ONLY IN REF"
            continue
        if in_new and not in_ref:
            failures[key] = "ONLY IN NEW"
            continue

        r_ref = layers_ref[key].merged()
        r_new = layers_new[key].merged()
        xor_area = (r_ref ^ r_new).area() * dbu * dbu
        if xor_area > 1e-6:
            failures[key] = (
                f"XOR={xor_area:.6f} um^2 "
                f"(ref={r_ref.area() * dbu * dbu:.4f}, "
                f"new={r_new.area() * dbu * dbu:.4f})"
            )
    return failures


# -----------------------------------------------------------------------
# Test matrices
# -----------------------------------------------------------------------

NMOS_PARAMS = list(
    itertools.product(
        [0.15, 0.22, 0.30, 0.60, 1.0],  # W
        [0.13, 0.25, 0.50],  # L
        [1, 2, 4],  # NG
    )
)

PMOS_PARAMS = list(
    itertools.product(
        [0.15, 0.22, 0.30, 0.60, 1.0],
        [0.13, 0.25, 0.50],
        [1, 2, 4],
    )
)

NMOSHV_PARAMS = list(
    itertools.product(
        [0.30, 0.60, 1.0, 2.0],
        [0.45, 0.70, 1.0],
        [1, 2, 4],
    )
)

PMOSHV_PARAMS = list(
    itertools.product(
        [0.30, 0.60, 1.0, 2.0],
        [0.40, 0.70, 1.0],
        [1, 2, 4],
    )
)


def _param_id(val):
    width, length, ng = val
    return f"W{width}_L{length}_NG{ng}"


# -----------------------------------------------------------------------
# nmos
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", NMOS_PARAMS, ids=[_param_id(p) for p in NMOS_PARAMS]
)
def test_xor_nmos(width, length, ng):
    ref = pycell.nmos(w=width, l=length, ng=ng)
    new = nmos(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# pmos
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", PMOS_PARAMS, ids=[_param_id(p) for p in PMOS_PARAMS]
)
def test_xor_pmos(width, length, ng):
    ref = pycell.pmos(w=width, l=length, ng=ng)
    new = pmos(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# nmosHV
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", NMOSHV_PARAMS, ids=[_param_id(p) for p in NMOSHV_PARAMS]
)
def test_xor_nmosHV(width, length, ng):
    ref = pycell.nmosHV(w=width, l=length, ng=ng)
    new = nmos_hv(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# pmosHV
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", PMOSHV_PARAMS, ids=[_param_id(p) for p in PMOSHV_PARAMS]
)
def test_xor_pmosHV(width, length, ng):
    ref = pycell.pmosHV(w=width, l=length, ng=ng)
    new = pmos_hv(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )
